# Generated by Django 5.1.4 on 2024-12-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecsite", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductPictures",
            new_name="ProductPicture",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="qty",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="価格"
            ),
        ),
    ]
