# Generated by Django 5.1.4 on 2024-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecsite", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("cakes", "魚介類"), ("bakedcakes", "野菜"), ("goods", "肉類")],
                max_length=20,
                verbose_name="種類",
            ),
        ),
    ]
